on: 
  push: 
    branches:
      - '**'

name: CI
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Check-out source code
        uses: actions/checkout@v2
    
      - name: Build
        run: ./gradlew build
          
      - name: Publish to OSSRH
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publishToOSSRH closeOSSRHStagingRepository
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PWD }}
          ORG_GRADLE_PROJECT_OSSRHUsername: ${{ secrets.OSSRH_USER_NAME }}
          ORG_GRADLE_PROJECT_OSSRHPassword: ${{ secrets.OSSRH_PASSWORD }}